site_name: COMFILE Documentation Library
theme:
  name: material
  language: ko  # 한국어 설정

nav:
  - 홈: index.md
  - 안전경고: warnning.md
  - 터치패널PC:
    - 윈도우 7/10/11: cpcv/index.md
    - 윈도우 CE: cuwin/index.md
  - 컴파일파이: comfilepi/index.md
  - HMI: hmi/index.md
  - 임베디드 컨트롤러:
    - 큐블록: cubloc/index.md    
    - 모아콘: moacon/index.md
    - 모듈형 FADUINO: modularfaduino/index.md
    - FADUINO: faduino/index.md
  - 디스플레이:
    - M Display: mdisplay/index.md
    - CLCD: clcd/index.md
    - CSG: csg/index.md
    - UIF-5K-2: uif5k2/index.md
    - UIF420B: uif420b/index.md

theme:
  name: material
  palette:
    # 낮 모드 / 밤 모드 설정
    - scheme: slate
      primary: black # 상단 바 색상
      accent: lime  # 강조 색상
    - scheme: slate
      primary: black
      accent: lime
  features:
    - navigation.sticky # 상단 메뉴바 고정
    - navigation.sections  # 왼쪽 메뉴를 섹션별로 구분해서 표시
    - navigation.expand    # 메뉴를 처음부터 다 펼쳐서 보여줌
    - toc.integrate        # (선택) 오른쪽 목차를 왼쪽 메뉴에 통합    
    - search.suggest  # 검색어 자동 완성
