name: COMFILE Documentation Library
on:
  push:
    branches: [ master ] # 본인의 방 이름이 main이면 main으로 수정!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 서버 접속 및 업데이트 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/comfiledocs
            git pull origin master
            mkdocs build
